language: php
php:
  - 7.0
  - 7.1
sudo: false
install:
  - composer install
before_script:
  - pushd public
  - DB=config ../vendor/bin/aerys -d -c index.php &
  - popd
  - sleep 4
script:
  - vendor/bin/phpunit
env:
  - DB=sqlite
